apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: airflow
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs  # Use your NFS storage class name
  resources:
    requests:
      storage: 10Gi
